config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcome#index'

  get 'welcome/index'

  resources :demographics
  resources :divisions
  resources :schools
  resources :scores do
    get 'chart', :on => :collection
  end

  # resources :solIds

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/codes.rb
module Codes

  @demo_codes = {
      5 => 'Hispanic Male',
      6 => 'Hispanic Female',
      7 => 'American Indian/Alaska Native Male',
      8 => 'American Indian/Alaska Native Female',
      9 => 'Asian Male',
      10 => 'Asian Female',
      11 => 'Black or African American Male',
      12 => 'Black or African American Female',
      13 => 'Native Hawaiian/Pacific Islander Male',
      14 => 'Native Hawaiian/Pacific Islander Female',
      15 => 'White Male',
      16 => 'White Female',
      17 => 'Two or more races  (Non-Hispanic) Male',
      18 => 'Two or more races (Non-Hispanic) Female',
      19 => 'Total Full-time Students',
      20 => 'Part-time Students',
      21 => 'All Students',
      100 => 'Female',
      101 => 'Male',
      102 => 'Black',
      103 => 'Hispanic',
      104 => 'White',
      105 => 'Asian',
      106 => 'Native Hawaiian',
      107 => 'American Indian',
      200 => 'Two or more races',
      201 => 'Students with Disabilities',
      202 => 'Economically Disadvantaged',
      203 => 'English Learners',
      204 => 'Migrant',
      205 => 'Homeless'
  }.freeze

  def self.demo_code(id)
    @demo_codes[id]
  end

  @level_codes = {
      0 => 'Fail',
      1 => 'Proficient',
      2 => 'Advanced'
  }.freeze

  def self.level_code(id)
    @level_codes[id]
  end

  @sol_demo_codes = {
      21 => 'All Students',
      100 => 'Female',
      101 => 'Male',
      102 => 'Black',
      103 => 'Hispanic',
      104 => 'White',
      105 => 'Asian',
      106 => 'Native Hawaiian',
      107 => 'American Indian',
      200 => 'Two or more races'
  }.freeze

  def self.get_sol_demo_codes
    @sol_demo_codes
  end

  @test_types = ['English: Reading', 'Mathematics', 'Science', 'Virginia Studies', 'Civics and Economics',
                 'English: Writing', 'Algebra I', 'Algebra II', 'Biology', 'Chemistry', 'Earth Science', 'Geometry',
                 'History and Social Science     (Alternate Assessment)', 'Mathematics     (Alternate Assessment)',
                 'Science     (Alternate Assessment)', 'Virginia and United States History', 'World History I',
                 'World History II', 'History and Social Science', 'World Geography'].freeze

  def self.get_test_types
    @test_types
  end

  @grades = [ '3', '4', '5', '6', '7', '8', 'High School', 'Content Specific' ]

  def self.get_grades
    @grades
  end

end

app/models/demographic.rb
require_relative 'codes.rb'

class Demographic < ApplicationRecord

  belongs_to :school

  include Codes

  def category_name
    Codes.demo_code(category)
  end

end

app/models/division.rb
class Division < ApplicationRecord

end

app/models/school.rb
class School < ApplicationRecord

  belongs_to :division

end

app/models/score.rb
require_relative 'codes.rb'

class Score < ApplicationRecord

  include Filterable

  belongs_to :school

  scope :school_id, -> (school_id) { where school_id: school_id }
  scope :school_year, -> (school_year) { where school_year: school_year }
  scope :test_type, -> (test_type) { where test_type: test_type }
  scope :grade, -> (grade) { where grade: grade }
  scope :result_level, -> (result_level) { where result_level: result_level }
  scope :subgroup, -> (subgroup) { where subgroup: subgroup }

  include Codes

  def subgroup_name
    Codes.demo_code(subgroup)
  end

  def result_level_name
    Codes.level_code(result_level)
  end

  # def as_json(options)
  #   super( :only => [ :school_id ] )
  # end
end

app/models/sol_id.rb
class SolId < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_api_controller.rb
 class BaseApiController < ApplicationController
    before_filter :parse_request

    private
       def parse_request
         @json = JSON.parse(request.body.read)
       end
    end

app/controllers/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/controllers/demographics_controller.rb
class DemographicsController < ApplicationController

  def index
    @ds = Demographic.all
  end

  def show
    @d = Demographic.find(params[:id])
  end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def index

    subgroups = params[:subgroup].split(',').map{|e| e.to_i}

    @scores = Score.filter(params.slice(:school_id, :school_year, :test_type, :grade, :result_level)).where(:subgroup => subgroups)

    p @scores

    respond_to do |format|
      format.html
      format.json { render json: @scores }
      format.jsonapi {
        hscores = Hash.new { |hash, key| hash[key] = Hash.new(&hash.default_proc) }
        @scores.each do |s|
          hscores[s.school_id][s.school_year][s.test_type][s.grade][s.subgroup][s.result_level] = s.percentage
        end

        fscores = []

        hscores.each do |school_id, results_by_year|
          results_by_year.each do |year, test_types|
            test_types.each do |test_type, by_grade|
              by_grade.each do |grade, demo|
                demo.each do |demo_code, percentages|
                  results = []
                  percentages.each do |level, percentage|
                    results << {:level => level, :percentage => percentage}
                  end
                  fscores << {:school_id => school_id,
                              :year => year, :type => test_type,
                              :grade => grade,
                              :dcode => demo_code,
                              :dcode_name => Codes.demo_code(demo_code),
                              :results => results}
                end
              end
            end
          end
        end

        render json: {:scores => fscores}
      }
    end

  end

  def show

    @score = Score.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @score }
    end

  end

  def chart

    @schools = School.includes(:division).order("divisions.name asc").order(:name)

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demographics_helper.rb
module DemographicsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/demographics/index.html.erb
<h1>Listing Demographics</h1>

<table border="1">
  <tr>
    <th>ID</th>
    <th>School Name</th>
    <th>District Name</th>
    <th>School Year</th>
    <th>Grade</th>
    <th>Category Name</th>
    <th>Count</th>
    <th>Link</th>
  </tr>

  <% @ds.each do |d| %>
      <tr>
          <td><%= d.id %></td>
          <td><%= d.school.nil? ? d.school_id.to_s : d.school.name %></td>
          <td><%= d.school.nil? or d.school.division.nil? ? d.district_id.to_s : d.school.division.name %></td>
          <td><%= d.school_year %></td>
          <td><%= d.grade %></td>
          <td><%= d.category_name %></td>
          <td><%= d.count %></td>
        <td><%= link_to 'Show', demographic_path(d) %></td>
      </tr>
  <% end %>
</table>

app/views/demographics/show.html.erb
<ul>
  <li>ID: <%= @d.id %> </li>
  <li>School ID: <%= @d.school_id %> </li>
  <li>School Year: <%= @d.school_year %> </li>
  <li>Grade: <%= @d.grade %> </li>
  <li>Category: <%= @d.category %> </li>
  <li>Count: <%= @d.count %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'/>
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0' />

    <title>Flare</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/chart.html.erb
<div class='page'>

  <!--
  <div class='menu-container'>
    <div class='menu'>
      <div class='date'>Aug 14, 2016</div>
      <div class='links'>

        <div class='signup'>Sign Up</div>
        <div class='login'>Login</div>
      </div>
    </div>
  </div>
  -->


  <header class='header-container'>
    <div class='header'>
      <div class='subscribe'><h1>Flare: Explore Virginia SOL Scores</h1></div>
      <!-- <div class='logo'><img src='images/awesome-logo.svg'/></div>
       <div class='social'><img src='images/social-icons.svg'/></div> -->
    </div>
    <nav>
      <ul>
        <li><a href='#'>Home</a></li>
        <li><a href='#'>About</a></li>
        <li><a href='#'>Nav1</a></li>
      </ul>
    </nav>
  </header>

  <div class="content-container">

    <div class="content-main">
      <div id="sidebar" class="sidebar">

        <%= form_tag("#", method: "get") do %>

            <%= select("", "sid", @schools.collect { |s| [s.division.name + " - " + s.name, s.id] }) %>

            <%= select("", "subgroup", Codes.get_sol_demo_codes.collect { |k, v| [v, k] }, {:selected => '21'}, {:multiple => true}) %>

            <%= select("", "test_type", Codes.get_test_types) %>

            <%= select("", "grade", Codes.get_grades) %>

        <% end %>

        <button class="button">
          Query
        </button>

      </div>

      <div id="chart" class="chart"></div>
    </div>

    <div id="json" class="json"></div>

  </div>

  <footer>&copy; 2017 Phil Varner</footer>

</div>


<script>

    var update = function (school_id, subgroup, test_type, grade) {
        $.ajax({
            url: 'http://localhost:3000/scores?school_id=' + school_id + '&grade=' + grade
            + '&subgroup=' + subgroup + '&test_type=' + test_type,
            dataType: 'jsonapi',
            accepts: {
                jsonapi: 'application/vnd.api+json'
            },
            converters: {
                'text jsonapi': function (r) {
                    return JSON.parse(r);
                }
            }
        })
            .fail(function (jqXHR, textStatus, errorThrown) {
                alert(errorThrown);
            })
            .done(function (msg) {
                $('#json').html('<pre>' + JSON.stringify(msg, null, '\t') + '</pre>');

                xaxis = [];
                $.each(msg['scores'], function (i, val) {
                    xaxis.push(val['year'] + " " + val['dcode_name']);
                });

                strata1 = ["Fail"];
                strata2 = ["Proficient"];
                strata3 = ["Advanced"];
                $.each(msg['scores'], function (i, val) {
                    strata1.push(val['results'][0]['percentage']);
                    strata2.push(val['results'][1]['percentage']);
                    strata3.push(val['results'][2]['percentage']);
                });

                var chart = c3.generate({
                    bindto: '#chart',
                    data: {
                        columns: [strata1, strata2, strata3],
                        type: 'bar',
                        groups: [[strata1[0], strata2[0], strata3[0]]],
                        order: null, // don't sort
                        colors: {
                            Fail: '#bae4b3',
                            Proficient: '#74c476',
                            Advanced: '#31a354'
                        }
                    },
                    axis: {
                        x: {
                            type: 'category',
                            categories: xaxis
                        },
                        y: {
                            max: 100,
                            padding: {top: 0, bottom: 0}
                        }
                    },
                    bar: {
                        width: 50
                    }
                });
            });
    };

    $.ready(
        $('.button').click(function (e) {
            update($('#_sid').val(), $('#_subgroup').val(), $('#_test_type').val(), $('#_grade').val());
        })
    );
</script>

app/views/scores/index.html.erb
<h1>Listing of Scores</h1>

<table border="1">
  <tr>
    <th>ID</th>
    <th>School</th>
    <th>Division</th>
    <th>School Year</th>
    <th>Grade</th>
    <th>Test Type</th>
    <th>Result Level</th>
    <th>Subgroup</th>
    <th>Percentage</th>
    <th>Link</th>
  </tr>

  <% @scores.each do |score| %>
      <tr>
        <td><%= score.id %></td>
        <td><%= score.school.nil? ? score.school_id.to_s : score.school.name %></td>
        <td><%= score.school.nil? || score.school.division.nil? ? score.district_id.to_s : score.school.division.name %></td>
        <td><%= score.school_year %></td>
        <td><%= score.grade %></td>
        <td><%= score.test_type %></td>
        <td><%= score.result_level_name %></td>
        <td><%= score.subgroup_name %></td>
        <td><%= score.percentage %></td>
        <td><%= link_to 'Show', score_path(score) %></td>
      </tr>
  <% end %>
</table>

app/views/scores/show.html.erb
<ul>
  <li>ID: <%= @score.id %> </li>
  <li>School ID: <%= @score.school_id %> </li>
  <li>School: <%= @score.school.nil? ? @score.school_id.to_s : @score.school.name %> </li>
  <li>District: <%= @score.school.nil? || @score.school.division.nil? ? @score.district_id.to_s : @score.school.division.name %></li>
  <li>School Year: <%= @score.school_year %> </li>
  <li>Grade: <%= @score.grade %> </li>
  <li>Test Type: <%= @score.test_type %> </li>
  <li>Result Level: <%= @score.result_level_name %> </li>
  <li>Subgroup: <%= @score.subgroup_name %> </li>
  <li>Percentage: <%= @score.percentage %> </li>
</ul>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>